title: "LEARNING MADE EASY"
author: "SONWA YONTI JULVANCE"
description: "The future of remote learning"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "LOGIN", icon: LOGIN, sidebaricon: LOGIN}
  - {file: "README.md", title: "HOME", icon: HOME, sidebaricon: HOME}
  - {title: "SCHOOL/FACULTY"}
  - {title: "BOOKS"}
  - {title: "Watch VIDEOS"}
  - {title: "SEARCH"}
  - {title: "DOWNLOADS"}
  - {title: "ASK FOR HELP"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "julvancesonwa64@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/easylearningmade/easylearning.github.io"}
  - {title: Login, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
